version: "0.1"
services:
  fish-diffusion:
    build: .
    env_file:
      - fish-diffusion-docker.env
    volumes:
      - type: bind
        source: ./dataset
        target: /root/fish-diffusion/dataset
    entrypoint: ["python3","train.py", "--config", "configs/svc_hubert_soft.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
