name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false
          poetry install
      - name: Lint with black and isort
        run: |
          poetry run python -m black . --check
          poetry run python -m isort . --check
